services:
  db:
    image: mariadb:10.6
    platform: linux/arm64
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psomewordpress"]
      timeout: 200s
      retries: 100

  wordpress:
    depends_on:
      db:
        condition: service_healthy
    image: wordpress:latest
    platform: linux/arm64
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    healthcheck:
      # This checks for a string that always appears on the login page, avoiding problems with redirects
      test: ["CMD", "curl", "-fsSL", "http://localhost/wp-login.php"]
      interval: 100ms
      timeout: 100s
      retries: 100

volumes:
  db_data:
  wordpress_data: