version: "3.8"

services:
  db:
    image: mariadb:10.6
    platform: linux/arm64
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    # Add a healthcheck to ensure the database is ready
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 20s
      retries: 10

  wordpress:
    # Use depends_on with condition to wait for the database healthcheck
    depends_on:
      db:
        condition: service_healthy
    image: wordpress:php8.2-apache
    platform: linux/arm64
    ports:
      - "8000:80"
    restart: always
    environment:
      # Change DB host to just the service name
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    # Map a volume for all WordPress files
    volumes:
      - wordpress_data:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/uploads.ini

volumes:
  db_data:
  wordpress_data:
